import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import './globals.css';

export const metadata: Metadata = {
  title: 'synchrone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
        <Toaster
          toastOptions={{
            style: {
              backgroundColor: '#171717',
              color: '#fafafa', 
            },
          }}
        />
      </body>
    </html>
  );
}
